name: Docker Image CI

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
  
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # need to switch to PAT for compatibility with gchr.io (save as secrets.GH_PAT)
    
    - 
      name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(cat VERSION)"
    
    - 
      name: Build & Push Docker image
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          file: Dockerfile_mkl
          build-args: |
            BOOST_IO=1
            LIB_INSTALL=libboost-iostreams-dev
            LIB_INSTALL2=libboost-iostreams-dev
            STATIC=1
          tags: rgcgithub/regenie:v${{ steps.getversion.outputs.version }}.gz
