name: Docker Image CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY: docker.pkg.github.com
  REPO_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
  
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:      
    - 
      name: Checkout repository
      uses: actions/checkout@v2

    - 
      name: Login to Docker
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: $GITHUB_ACTOR
          password: ${{ secrets.GH_PAT }}

    - 
      name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(cat VERSION)"
    
    - 
      name: Build & Push Docker image
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          file: Dockerfile_mkl
          build-args: |
            BOOST_IO=1
            LIB_INSTALL=libboost-iostreams-dev
            LIB_INSTALL2=libboost-iostreams-dev
            STATIC=1
          tags: ${{ env.REPO_NAME }}:v${{ steps.getversion.outputs.version }}.gz
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GH_PAT }}
